//! MaintenanceRequest trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MaintenanceRequest;

pub type MaintenanceRequestTriggerEvent      = TriggerEvent;
pub type MaintenanceRequestTriggerContext    = TriggerContext<MaintenanceRequest>;
pub type MaintenanceRequestTriggerContextMut = TriggerContextMut<MaintenanceRequest>;
pub type MaintenanceRequestActionExecutor    = ActionExecutor;
pub type MaintenanceRequestTriggerRegistry   = TriggerRegistry<MaintenanceRequest>;
pub type MaintenanceRequestTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MaintenanceRequest>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for MaintenanceRequest.
pub fn maintenance_request_trigger_registry() -> MaintenanceRequestTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
