//! Bulk operations for MaintenanceSchedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateMaintenanceScheduleDto;
use crate::application::service::MaintenanceScheduleService;
use crate::domain::entity::MaintenanceSchedule;

/// Bulk operation handler for MaintenanceSchedule entities.
///
/// Wraps `MaintenanceScheduleService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type MaintenanceScheduleBulkService = GenericBulkService<MaintenanceSchedule, CreateMaintenanceScheduleDto, MaintenanceScheduleService>;

// <<< CUSTOM
// END CUSTOM
