//! Bulk operations for MaintenanceVisitPart entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateMaintenanceVisitPartDto;
use crate::application::service::MaintenanceVisitPartService;
use crate::domain::entity::MaintenanceVisitPart;

/// Bulk operation handler for MaintenanceVisitPart entities.
///
/// Wraps `MaintenanceVisitPartService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type MaintenanceVisitPartBulkService = GenericBulkService<MaintenanceVisitPart, CreateMaintenanceVisitPartDto, MaintenanceVisitPartService>;

// <<< CUSTOM
// END CUSTOM
