//! Bulk operations for MaintenanceVisit entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateMaintenanceVisitDto;
use crate::application::service::MaintenanceVisitService;
use crate::domain::entity::MaintenanceVisit;

/// Bulk operation handler for MaintenanceVisit entities.
///
/// Wraps `MaintenanceVisitService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type MaintenanceVisitBulkService = GenericBulkService<MaintenanceVisit, CreateMaintenanceVisitDto, MaintenanceVisitService>;

// <<< CUSTOM
// END CUSTOM
