//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod maintenance_schedule_bulk;
pub mod maintenance_visit_bulk;
pub mod maintenance_visit_part_bulk;

pub use maintenance_schedule_bulk::MaintenanceScheduleBulkService;
pub use maintenance_visit_bulk::MaintenanceVisitBulkService;
pub use maintenance_visit_part_bulk::MaintenanceVisitPartBulkService;

// <<< CUSTOM
// END CUSTOM
