//! MaintenanceSchedule DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MaintenanceSchedule;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MaintenanceSchedule
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMaintenanceScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "interval_days")]
    pub interval_days: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "next_due_date")]
    pub next_due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MaintenanceSchedule
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMaintenanceScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "interval_days")]
    pub interval_days: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "next_due_date")]
    pub next_due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MaintenanceSchedule
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMaintenanceScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_id")]
    pub asset_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "interval_days")]
    pub interval_days: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "next_due_date")]
    pub next_due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchMaintenanceScheduleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.asset_id.is_some() || self.name.is_some() || self.interval_days.is_some() || self.next_due_date.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MaintenanceSchedule entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceScheduleResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub interval_days: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub next_due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MaintenanceSchedule entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceScheduleListResponseDto {
    /// List of items
    pub items: Vec<MaintenanceScheduleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MaintenanceScheduleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MaintenanceScheduleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceScheduleSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_id: Uuid,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MaintenanceSchedule> for MaintenanceScheduleResponseDto {
    fn from(entity: MaintenanceSchedule) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            name: entity.name,
            interval_days: entity.interval_days,
            next_due_date: entity.next_due_date,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<MaintenanceSchedule> for MaintenanceScheduleSummaryDto {
    fn from(entity: MaintenanceSchedule) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateMaintenanceScheduleDto> for MaintenanceSchedule {
    fn from(dto: CreateMaintenanceScheduleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            asset_id: dto.asset_id,
            name: dto.name,
            interval_days: dto.interval_days,
            next_due_date: dto.next_due_date,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MaintenanceSchedule> for MaintenanceScheduleResponseDto {
    fn from(entity: &MaintenanceSchedule) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            asset_id: entity.asset_id.clone(),
            name: entity.name.clone(),
            interval_days: entity.interval_days.clone(),
            next_due_date: entity.next_due_date.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMaintenanceScheduleDto> for MaintenanceSchedule {
    fn from_create_dto(dto: CreateMaintenanceScheduleDto) -> backbone_core::ServiceResult<Self> {
        Ok(MaintenanceSchedule::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMaintenanceScheduleDto> for MaintenanceSchedule {
    fn apply_update(mut self, dto: UpdateMaintenanceScheduleDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.asset_id = dto.asset_id;
        self.name = dto.name;
        self.interval_days = dto.interval_days;
        self.next_due_date = dto.next_due_date;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MaintenanceSchedule here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
