//! MaintenanceVisit DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MaintenanceVisit;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::MaintenanceType;
use crate::domain::entity::VisitStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MaintenanceVisit
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMaintenanceVisitDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "schedule_id")]
    pub schedule_id: Option<Uuid>,
    #[serde(alias = "maintenance_type")]
    pub maintenance_type: MaintenanceType,
    pub status: VisitStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warranty_claim_id")]
    pub warranty_claim_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "scheduled_date")]
    pub scheduled_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "performed_date")]
    pub performed_date: Option<NaiveDate>,
    #[serde(alias = "labor_cost")]
    pub labor_cost: Decimal,
    #[serde(alias = "parts_cost")]
    pub parts_cost: Decimal,
    #[serde(alias = "total_cost")]
    pub total_cost: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "maintenance_expense_account_id")]
    pub maintenance_expense_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parts_inventory_account_id")]
    pub parts_inventory_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "labor_payable_account_id")]
    pub labor_payable_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MaintenanceVisit
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMaintenanceVisitDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "schedule_id")]
    pub schedule_id: Option<Uuid>,
    #[serde(alias = "maintenance_type")]
    pub maintenance_type: MaintenanceType,
    pub status: VisitStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warranty_claim_id")]
    pub warranty_claim_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "scheduled_date")]
    pub scheduled_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "performed_date")]
    pub performed_date: Option<NaiveDate>,
    #[serde(alias = "labor_cost")]
    pub labor_cost: Decimal,
    #[serde(alias = "parts_cost")]
    pub parts_cost: Decimal,
    #[serde(alias = "total_cost")]
    pub total_cost: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "maintenance_expense_account_id")]
    pub maintenance_expense_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parts_inventory_account_id")]
    pub parts_inventory_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "labor_payable_account_id")]
    pub labor_payable_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MaintenanceVisit
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMaintenanceVisitDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_id")]
    pub asset_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "schedule_id")]
    pub schedule_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "maintenance_type")]
    pub maintenance_type: Option<MaintenanceType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<VisitStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warranty_claim_id")]
    pub warranty_claim_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scheduled_date")]
    pub scheduled_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "performed_date")]
    pub performed_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "labor_cost")]
    pub labor_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parts_cost")]
    pub parts_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_cost")]
    pub total_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "maintenance_expense_account_id")]
    pub maintenance_expense_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parts_inventory_account_id")]
    pub parts_inventory_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "labor_payable_account_id")]
    pub labor_payable_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchMaintenanceVisitDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.asset_id.is_some() || self.schedule_id.is_some() || self.maintenance_type.is_some() || self.status.is_some() || self.warehouse_id.is_some() || self.warranty_claim_id.is_some() || self.scheduled_date.is_some() || self.performed_date.is_some() || self.labor_cost.is_some() || self.parts_cost.is_some() || self.total_cost.is_some() || self.maintenance_expense_account_id.is_some() || self.parts_inventory_account_id.is_some() || self.labor_payable_account_id.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MaintenanceVisit entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceVisitResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub asset_id: Uuid,
    pub schedule_id: Option<Uuid>,
    pub maintenance_type: MaintenanceType,
    pub status: VisitStatus,
    pub warehouse_id: Option<Uuid>,
    pub warranty_claim_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub scheduled_date: NaiveDate,
    pub performed_date: Option<NaiveDate>,
    pub labor_cost: Decimal,
    pub parts_cost: Decimal,
    pub total_cost: Decimal,
    pub maintenance_expense_account_id: Option<Uuid>,
    pub parts_inventory_account_id: Option<Uuid>,
    pub labor_payable_account_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MaintenanceVisit entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceVisitListResponseDto {
    /// List of items
    pub items: Vec<MaintenanceVisitResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MaintenanceVisitListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MaintenanceVisitResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceVisitSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_id: Uuid,
    pub schedule_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MaintenanceVisit> for MaintenanceVisitResponseDto {
    fn from(entity: MaintenanceVisit) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            schedule_id: entity.schedule_id,
            maintenance_type: entity.maintenance_type,
            status: entity.status,
            warehouse_id: entity.warehouse_id,
            warranty_claim_id: entity.warranty_claim_id,
            scheduled_date: entity.scheduled_date,
            performed_date: entity.performed_date,
            labor_cost: entity.labor_cost,
            parts_cost: entity.parts_cost,
            total_cost: entity.total_cost,
            maintenance_expense_account_id: entity.maintenance_expense_account_id,
            parts_inventory_account_id: entity.parts_inventory_account_id,
            labor_payable_account_id: entity.labor_payable_account_id,
            journal_id: entity.journal_id,
            accounting_post_id: entity.accounting_post_id,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<MaintenanceVisit> for MaintenanceVisitSummaryDto {
    fn from(entity: MaintenanceVisit) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            schedule_id: entity.schedule_id,
            created_at,
        }
    }
}

impl From<CreateMaintenanceVisitDto> for MaintenanceVisit {
    fn from(dto: CreateMaintenanceVisitDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            asset_id: dto.asset_id,
            schedule_id: dto.schedule_id,
            maintenance_type: dto.maintenance_type,
            status: dto.status,
            warehouse_id: dto.warehouse_id,
            warranty_claim_id: dto.warranty_claim_id,
            scheduled_date: dto.scheduled_date,
            performed_date: dto.performed_date,
            labor_cost: dto.labor_cost,
            parts_cost: dto.parts_cost,
            total_cost: dto.total_cost,
            maintenance_expense_account_id: dto.maintenance_expense_account_id,
            parts_inventory_account_id: dto.parts_inventory_account_id,
            labor_payable_account_id: dto.labor_payable_account_id,
            journal_id: dto.journal_id,
            accounting_post_id: dto.accounting_post_id,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MaintenanceVisit> for MaintenanceVisitResponseDto {
    fn from(entity: &MaintenanceVisit) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            asset_id: entity.asset_id.clone(),
            schedule_id: entity.schedule_id.clone(),
            maintenance_type: entity.maintenance_type.clone(),
            status: entity.status.clone(),
            warehouse_id: entity.warehouse_id.clone(),
            warranty_claim_id: entity.warranty_claim_id.clone(),
            scheduled_date: entity.scheduled_date.clone(),
            performed_date: entity.performed_date.clone(),
            labor_cost: entity.labor_cost.clone(),
            parts_cost: entity.parts_cost.clone(),
            total_cost: entity.total_cost.clone(),
            maintenance_expense_account_id: entity.maintenance_expense_account_id.clone(),
            parts_inventory_account_id: entity.parts_inventory_account_id.clone(),
            labor_payable_account_id: entity.labor_payable_account_id.clone(),
            journal_id: entity.journal_id.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMaintenanceVisitDto> for MaintenanceVisit {
    fn from_create_dto(dto: CreateMaintenanceVisitDto) -> backbone_core::ServiceResult<Self> {
        Ok(MaintenanceVisit::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMaintenanceVisitDto> for MaintenanceVisit {
    fn apply_update(mut self, dto: UpdateMaintenanceVisitDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.asset_id = dto.asset_id;
        self.schedule_id = dto.schedule_id;
        self.maintenance_type = dto.maintenance_type;
        self.status = dto.status;
        self.warehouse_id = dto.warehouse_id;
        self.warranty_claim_id = dto.warranty_claim_id;
        self.scheduled_date = dto.scheduled_date;
        self.performed_date = dto.performed_date;
        self.labor_cost = dto.labor_cost;
        self.parts_cost = dto.parts_cost;
        self.total_cost = dto.total_cost;
        self.maintenance_expense_account_id = dto.maintenance_expense_account_id;
        self.parts_inventory_account_id = dto.parts_inventory_account_id;
        self.labor_payable_account_id = dto.labor_payable_account_id;
        self.journal_id = dto.journal_id;
        self.accounting_post_id = dto.accounting_post_id;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MaintenanceVisit here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
