//! MaintenanceStage DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MaintenanceStage;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MaintenanceStage
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMaintenanceStageDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MaintenanceStage
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMaintenanceStageDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MaintenanceStage
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMaintenanceStageDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fold: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
}

impl PatchMaintenanceStageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.sequence.is_some() || self.fold.is_some() || self.done.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MaintenanceStage entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceStageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub fold: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub done: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MaintenanceStage entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceStageListResponseDto {
    /// List of items
    pub items: Vec<MaintenanceStageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MaintenanceStageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MaintenanceStageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaintenanceStageSummaryDto {
    pub id: Uuid,
    pub company_id: Option<Uuid>,
    pub name: String,
    pub sequence: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MaintenanceStage> for MaintenanceStageResponseDto {
    fn from(entity: MaintenanceStage) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            sequence: entity.sequence,
            fold: entity.fold,
            done: entity.done,
            metadata: entity.metadata,
        }
    }
}

impl From<MaintenanceStage> for MaintenanceStageSummaryDto {
    fn from(entity: MaintenanceStage) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            sequence: entity.sequence,
            created_at,
        }
    }
}

impl From<CreateMaintenanceStageDto> for MaintenanceStage {
    fn from(dto: CreateMaintenanceStageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            sequence: dto.sequence,
            fold: dto.fold,
            done: dto.done,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MaintenanceStage> for MaintenanceStageResponseDto {
    fn from(entity: &MaintenanceStage) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            sequence: entity.sequence.clone(),
            fold: entity.fold.clone(),
            done: entity.done.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMaintenanceStageDto> for MaintenanceStage {
    fn from_create_dto(dto: CreateMaintenanceStageDto) -> backbone_core::ServiceResult<Self> {
        Ok(MaintenanceStage::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMaintenanceStageDto> for MaintenanceStage {
    fn apply_update(mut self, dto: UpdateMaintenanceStageDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.sequence = dto.sequence;
        self.fold = dto.fold;
        self.done = dto.done;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MaintenanceStage here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
