//! Domain policy for MaintenanceRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::MaintenanceRequest;

/// Domain policy for MaintenanceRequest — enforces business invariants.
pub struct MaintenanceRequestDomainPolicy;

#[async_trait]
impl DomainPolicy<MaintenanceRequest> for MaintenanceRequestDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // Example:
    // async fn can_delete(&self, entity: &MaintenanceRequest) -> PolicyDecision {
    //     if entity.is_locked {
    //         Err("locked maintenance_request cannot be deleted".into())
    //     } else { Ok(true) }
    // }
    // END CUSTOM
}
