//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod maintenance_schedule_domain_policy;
pub mod maintenance_visit_domain_policy;
pub mod maintenance_visit_part_domain_policy;

pub use maintenance_schedule_domain_policy::MaintenanceScheduleDomainPolicy;
pub use maintenance_visit_domain_policy::MaintenanceVisitDomainPolicy;
pub use maintenance_visit_part_domain_policy::MaintenanceVisitPartDomainPolicy;

// <<< CUSTOM
// END CUSTOM
