//! Application service for MaintenanceStage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `maintenance_stage_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMaintenanceStageDto, UpdateMaintenanceStageDto};
use crate::domain::entity::MaintenanceStage;
use crate::infrastructure::persistence::MaintenanceStageRepository;

/// Application service for MaintenanceStage entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `maintenance_stage_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MaintenanceStageServiceCustom {
///     inner: Arc<MaintenanceStageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MaintenanceStageService = GenericCrudService<
    MaintenanceStage,
    CreateMaintenanceStageDto,
    UpdateMaintenanceStageDto,
    MaintenanceStageRepository,
>;

// <<< CUSTOM
// END CUSTOM
