//! Application service for MaintenanceSchedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `maintenance_schedule_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMaintenanceScheduleDto, UpdateMaintenanceScheduleDto};
use crate::domain::entity::MaintenanceSchedule;
use crate::infrastructure::persistence::MaintenanceScheduleRepository;

/// Application service for MaintenanceSchedule entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `maintenance_schedule_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MaintenanceScheduleServiceCustom {
///     inner: Arc<MaintenanceScheduleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MaintenanceScheduleService = GenericCrudService<
    MaintenanceSchedule,
    CreateMaintenanceScheduleDto,
    UpdateMaintenanceScheduleDto,
    MaintenanceScheduleRepository,
>;

// <<< CUSTOM
// END CUSTOM
