//! Application service for MaintenanceVisitPart entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `maintenance_visit_part_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMaintenanceVisitPartDto, UpdateMaintenanceVisitPartDto};
use crate::domain::entity::MaintenanceVisitPart;
use crate::infrastructure::persistence::MaintenanceVisitPartRepository;

/// Application service for MaintenanceVisitPart entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `maintenance_visit_part_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MaintenanceVisitPartServiceCustom {
///     inner: Arc<MaintenanceVisitPartService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MaintenanceVisitPartService = GenericCrudService<
    MaintenanceVisitPart,
    CreateMaintenanceVisitPartDto,
    UpdateMaintenanceVisitPartDto,
    MaintenanceVisitPartRepository,
>;

// <<< CUSTOM
// END CUSTOM
