//! Application service for MaintenanceRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `maintenance_request_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMaintenanceRequestDto, UpdateMaintenanceRequestDto};
use crate::domain::entity::MaintenanceRequest;
use crate::infrastructure::persistence::MaintenanceRequestRepository;

/// Application service for MaintenanceRequest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `maintenance_request_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MaintenanceRequestServiceCustom {
///     inner: Arc<MaintenanceRequestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MaintenanceRequestService = GenericCrudService<
    MaintenanceRequest,
    CreateMaintenanceRequestDto,
    UpdateMaintenanceRequestDto,
    MaintenanceRequestRepository,
>;

// <<< CUSTOM
// END CUSTOM
