//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod maintenance_schedule_service;
pub mod maintenance_visit_service;
pub mod maintenance_visit_part_service;

// <<< CUSTOM
pub mod maintenance_gl;
pub mod maintenance_ports;
pub mod maintenance_events;
pub mod maintenance_write_service;
pub mod maintenance_query_service;
// END CUSTOM

pub use maintenance_schedule_service::MaintenanceScheduleService;
pub use maintenance_visit_service::MaintenanceVisitService;
pub use maintenance_visit_part_service::MaintenanceVisitPartService;
// <<< CUSTOM
pub use maintenance_gl::{AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink};
pub use maintenance_ports::{InventoryPort, InventoryRejected, IssueAck, IssueLine, IssuedLineValue, PartsIssue};
pub use maintenance_events::{LoggingSink, MaintenanceCompleted, MaintenanceEvent, MaintenanceEventSink};
pub use maintenance_write_service::{CompleteOutcome, MaintenanceError, MaintenanceWriteService, NewSchedule, NewVisit};
pub use maintenance_query_service::MaintenanceQueryServiceImpl;
// END CUSTOM