-- MaintenanceStage Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the maintenance.maintenance_stages table.
-- Customize this file to add your initial data.

-- <<< CUSTOM SEED DATA >>>
-- The one shared stage set (NULL company_id — visible to every company session; see the
-- fence posture map in schema/models/index.model.yaml). Fixed ids so callers (and tests)
-- can address the seeded stages deterministically. Idempotent: re-running is a no-op.
--
-- Mirrors the Odoo default stages New Request / In Progress / Repaired / Scrap: entering
-- Repaired or Scrap closes a request (done = true is the canonical closed flag) and, for a
-- preventive recurring request, spawns the successor. Odoo's numeric stage ids skip
-- stage_2 upstream (a cosmetic gap); the four rows here carry contiguous sequences
-- instead — the gap is not replicated.
INSERT INTO maintenance.maintenance_stages (id, company_id, name, sequence, fold, done, metadata) VALUES
    ('00000000-0000-0000-0000-00000000b001', NULL, 'New Request',  1, FALSE, FALSE, '{}'::jsonb),
    ('00000000-0000-0000-0000-00000000b002', NULL, 'In Progress',  2, FALSE, FALSE, '{}'::jsonb),
    ('00000000-0000-0000-0000-00000000b003', NULL, 'Repaired',     3, FALSE, TRUE,  '{}'::jsonb),
    ('00000000-0000-0000-0000-00000000b004', NULL, 'Scrap',        4, FALSE, TRUE,  '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;
