-- MaintenanceVisit Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the maintenance.maintenance_visits table.
-- Customize this file to add your initial data.

-- INSERT INTO maintenance.maintenance_visits (
--     id,
--     company_id,
--     asset_id,
--     schedule_id,
--     maintenance_type,
--     status,
--     warehouse_id,
--     warranty_claim_id,
--     scheduled_date,
--     performed_date,
--     labor_cost,
--     parts_cost,
--     total_cost,
--     maintenance_expense_account_id,
--     parts_inventory_account_id,
--     labor_payable_account_id,
--     journal_id,
--     accounting_post_id,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO maintenance.maintenance_visits (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

