-- MaintenanceRequest Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the maintenance.maintenance_requests table.
-- Customize this file to add your initial data.

-- INSERT INTO maintenance.maintenance_requests (
--     id,
--     company_id,
--     name,
--     description,
--     request_date,
--     schedule_date,
--     schedule_end,
--     close_date,
--     duration,
--     owner_user_id,
--     user_id,
--     asset_id,
--     stage_id,
--     kanban_state,
--     priority,
--     maintenance_type,
--     recurring,
--     repeat_interval,
--     repeat_unit,
--     repeat_type,
--     repeat_until,
--     successor_request_id,
--     successor_of_request_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO maintenance.maintenance_requests (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

