-- MaintenanceVisitPart Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the maintenance.maintenance_visit_parts table.
-- Customize this file to add your initial data.

-- INSERT INTO maintenance.maintenance_visit_parts (
--     id,
--     visit_id,
--     item_id,
--     quantity,
--     unit_cost,
--     amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO maintenance.maintenance_visit_parts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

