-- Company RLS fence for maintenance module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for maintenance.maintenance_schedules
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE maintenance.maintenance_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance.maintenance_schedules FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS maintenance_schedules_company_isolation ON maintenance.maintenance_schedules;
CREATE POLICY maintenance_schedules_company_isolation ON maintenance.maintenance_schedules
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for maintenance.maintenance_visits
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE maintenance.maintenance_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance.maintenance_visits FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS maintenance_visits_company_isolation ON maintenance.maintenance_visits;
CREATE POLICY maintenance_visits_company_isolation ON maintenance.maintenance_visits
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

