-- Migration: Create maintenance_schedules table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS maintenance;

CREATE TABLE IF NOT EXISTS maintenance.maintenance_schedules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    asset_id UUID NOT NULL,
    name TEXT NOT NULL,
    interval_days INTEGER NOT NULL,
    next_due_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_company_id_asset_id ON maintenance.maintenance_schedules (company_id, asset_id);

CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_is_active_next_due_date ON maintenance.maintenance_schedules (is_active, next_due_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_metadata_gin ON maintenance.maintenance_schedules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_metadata_deleted_at ON maintenance.maintenance_schedules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_metadata_created_at ON maintenance.maintenance_schedules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_schedules_metadata_updated_at ON maintenance.maintenance_schedules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION maintenance.maintenance_schedules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_schedules_insert_audit ON maintenance.maintenance_schedules;
CREATE TRIGGER maintenance_schedules_insert_audit BEFORE INSERT ON maintenance.maintenance_schedules
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_schedules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_schedules_update_audit ON maintenance.maintenance_schedules;
CREATE TRIGGER maintenance_schedules_update_audit BEFORE UPDATE ON maintenance.maintenance_schedules
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_schedules_audit_timestamp();
