-- Migration: Create maintenance_visit_parts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS maintenance;

CREATE TABLE IF NOT EXISTS maintenance.maintenance_visit_parts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    visit_id UUID NOT NULL,
    item_id UUID NOT NULL,
    quantity NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    unit_cost NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_visit_parts_visit_id ON maintenance.maintenance_visit_parts (visit_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_maintenance_visit_parts_metadata_gin ON maintenance.maintenance_visit_parts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_maintenance_visit_parts_metadata_deleted_at ON maintenance.maintenance_visit_parts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_visit_parts_metadata_created_at ON maintenance.maintenance_visit_parts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_visit_parts_metadata_updated_at ON maintenance.maintenance_visit_parts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_visit_parts_insert_audit ON maintenance.maintenance_visit_parts;
CREATE TRIGGER maintenance_visit_parts_insert_audit BEFORE INSERT ON maintenance.maintenance_visit_parts
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_visit_parts_update_audit ON maintenance.maintenance_visit_parts;
CREATE TRIGGER maintenance_visit_parts_update_audit BEFORE UPDATE ON maintenance.maintenance_visit_parts
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp();
