-- Migration: Create maintenance_stages table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS maintenance;

CREATE TABLE IF NOT EXISTS maintenance.maintenance_stages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 20,
    fold BOOLEAN NOT NULL DEFAULT FALSE,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_stages_sequence_id ON maintenance.maintenance_stages (sequence, id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_maintenance_stages_metadata_gin ON maintenance.maintenance_stages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_maintenance_stages_metadata_deleted_at ON maintenance.maintenance_stages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_stages_metadata_created_at ON maintenance.maintenance_stages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_stages_metadata_updated_at ON maintenance.maintenance_stages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION maintenance.maintenance_stages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_stages_insert_audit ON maintenance.maintenance_stages;
CREATE TRIGGER maintenance_stages_insert_audit BEFORE INSERT ON maintenance.maintenance_stages
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_stages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_stages_update_audit ON maintenance.maintenance_stages;
CREATE TRIGGER maintenance_stages_update_audit BEFORE UPDATE ON maintenance.maintenance_stages
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_stages_audit_timestamp();
