-- Audit Triggers Migration for maintenance module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: MaintenanceSchedule (maintenance.maintenance_schedules)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION maintenance.maintenance_schedules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_schedules_insert_audit ON maintenance.maintenance_schedules;
CREATE TRIGGER maintenance_schedules_insert_audit BEFORE INSERT ON maintenance.maintenance_schedules
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_schedules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_schedules_update_audit ON maintenance.maintenance_schedules;
CREATE TRIGGER maintenance_schedules_update_audit BEFORE UPDATE ON maintenance.maintenance_schedules
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_schedules_audit_timestamp();

-- ==============================================================================
-- Table: MaintenanceVisit (maintenance.maintenance_visits)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION maintenance.maintenance_visits_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_visits_insert_audit ON maintenance.maintenance_visits;
CREATE TRIGGER maintenance_visits_insert_audit BEFORE INSERT ON maintenance.maintenance_visits
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visits_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_visits_update_audit ON maintenance.maintenance_visits;
CREATE TRIGGER maintenance_visits_update_audit BEFORE UPDATE ON maintenance.maintenance_visits
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visits_audit_timestamp();

-- ==============================================================================
-- Table: MaintenanceVisitPart (maintenance.maintenance_visit_parts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_visit_parts_insert_audit ON maintenance.maintenance_visit_parts;
CREATE TRIGGER maintenance_visit_parts_insert_audit BEFORE INSERT ON maintenance.maintenance_visit_parts
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_visit_parts_update_audit ON maintenance.maintenance_visit_parts;
CREATE TRIGGER maintenance_visit_parts_update_audit BEFORE UPDATE ON maintenance.maintenance_visit_parts
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visit_parts_audit_timestamp();

