-- Migration: Create maintenance_visits table
-- Generated by metaphor-schema

-- Create maintenance_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'maintenance_type') THEN
        CREATE TYPE maintenance_type AS ENUM ('preventive', 'corrective');
    END IF;
END
$$;

-- Create visit_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'visit_status') THEN
        CREATE TYPE visit_status AS ENUM ('planned', 'in_progress', 'completed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS maintenance;

CREATE TABLE IF NOT EXISTS maintenance.maintenance_visits (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    asset_id UUID NOT NULL,
    schedule_id UUID,
    maintenance_type maintenance_type NOT NULL DEFAULT 'preventive',
    status visit_status NOT NULL DEFAULT 'planned',
    warehouse_id UUID,
    warranty_claim_id UUID,
    scheduled_date DATE NOT NULL,
    performed_date DATE,
    labor_cost NUMERIC NOT NULL DEFAULT 0,
    parts_cost NUMERIC NOT NULL DEFAULT 0,
    total_cost NUMERIC NOT NULL DEFAULT 0,
    maintenance_expense_account_id UUID,
    parts_inventory_account_id UUID,
    labor_payable_account_id UUID,
    journal_id UUID,
    accounting_post_id UUID,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_visits_company_id_asset_id ON maintenance.maintenance_visits (company_id, asset_id);

CREATE INDEX IF NOT EXISTS idx_maintenance_visits_status ON maintenance.maintenance_visits (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_maintenance_visits_metadata_gin ON maintenance.maintenance_visits USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_maintenance_visits_metadata_deleted_at ON maintenance.maintenance_visits ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_visits_metadata_created_at ON maintenance.maintenance_visits ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_visits_metadata_updated_at ON maintenance.maintenance_visits ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION maintenance.maintenance_visits_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_visits_insert_audit ON maintenance.maintenance_visits;
CREATE TRIGGER maintenance_visits_insert_audit BEFORE INSERT ON maintenance.maintenance_visits
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visits_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_visits_update_audit ON maintenance.maintenance_visits;
CREATE TRIGGER maintenance_visits_update_audit BEFORE UPDATE ON maintenance.maintenance_visits
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_visits_audit_timestamp();
