-- Migration: Create maintenance_requests table
-- Generated by metaphor-schema

-- Create request_kanban_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'request_kanban_state') THEN
        CREATE TYPE request_kanban_state AS ENUM ('normal', 'blocked', 'done');
    END IF;
END
$$;

-- Create request_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'request_priority') THEN
        CREATE TYPE request_priority AS ENUM ('very_low', 'low', 'normal', 'high');
    END IF;
END
$$;

-- Create maintenance_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'maintenance_type') THEN
        CREATE TYPE maintenance_type AS ENUM ('preventive', 'corrective');
    END IF;
END
$$;

-- Create repeat_unit enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'repeat_unit') THEN
        CREATE TYPE repeat_unit AS ENUM ('day', 'week', 'month', 'year');
    END IF;
END
$$;

-- Create repeat_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'repeat_type') THEN
        CREATE TYPE repeat_type AS ENUM ('forever', 'until');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS maintenance;

CREATE TABLE IF NOT EXISTS maintenance.maintenance_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    request_date DATE NOT NULL DEFAULT 'today',
    schedule_date TIMESTAMPTZ,
    schedule_end TIMESTAMPTZ,
    close_date DATE,
    duration NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (duration >= 0),
    owner_user_id UUID,
    user_id UUID,
    asset_id UUID,
    stage_id UUID NOT NULL,
    kanban_state request_kanban_state NOT NULL DEFAULT 'normal',
    priority request_priority NOT NULL,
    maintenance_type maintenance_type NOT NULL DEFAULT 'corrective',
    recurring BOOLEAN NOT NULL DEFAULT FALSE,
    repeat_interval INTEGER NOT NULL DEFAULT 1,
    repeat_unit repeat_unit NOT NULL DEFAULT 'week',
    repeat_type repeat_type NOT NULL DEFAULT 'forever',
    repeat_until DATE,
    successor_request_id UUID,
    successor_of_request_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_requests_stage_id ON maintenance.maintenance_requests (stage_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_maintenance_requests_successor_of_request_id ON maintenance.maintenance_requests (successor_of_request_id) WHERE successor_of_request_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_maintenance_requests_metadata_gin ON maintenance.maintenance_requests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_maintenance_requests_metadata_deleted_at ON maintenance.maintenance_requests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_requests_metadata_created_at ON maintenance.maintenance_requests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_maintenance_requests_metadata_updated_at ON maintenance.maintenance_requests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION maintenance.maintenance_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS maintenance_requests_insert_audit ON maintenance.maintenance_requests;
CREATE TRIGGER maintenance_requests_insert_audit BEFORE INSERT ON maintenance.maintenance_requests
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS maintenance_requests_update_audit ON maintenance.maintenance_requests;
CREATE TRIGGER maintenance_requests_update_audit BEFORE UPDATE ON maintenance.maintenance_requests
    FOR EACH ROW EXECUTE FUNCTION maintenance.maintenance_requests_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE maintenance.maintenance_requests ADD CONSTRAINT fk_maintenance_requests_stage_id FOREIGN KEY (stage_id) REFERENCES maintenance.maintenance_stages (id);
