-- Enum types for maintenance module
-- Generated by metaphor-schema

-- Create maintenance_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'maintenance_type') THEN
        CREATE TYPE maintenance_type AS ENUM ('preventive', 'corrective');
    END IF;
END
$$;

-- Create visit_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'visit_status') THEN
        CREATE TYPE visit_status AS ENUM ('planned', 'in_progress', 'completed', 'cancelled');
    END IF;
END
$$;

