//! Event handler trait for MaintenanceRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaintenanceRequestEvent;

/// Event handler for MaintenanceRequest events.
/// Implement this trait to react to MaintenanceRequest lifecycle events.
pub trait MaintenanceRequestEventHandler: EventHandler<MaintenanceRequestEvent> {}
