//! Event handler trait for MaintenanceVisitPart events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaintenanceVisitPartEvent;

/// Event handler for MaintenanceVisitPart events.
/// Implement this trait to react to MaintenanceVisitPart lifecycle events.
pub trait MaintenanceVisitPartEventHandler: EventHandler<MaintenanceVisitPartEvent> {}
