//! Event handler trait for MaintenanceSchedule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaintenanceScheduleEvent;

/// Event handler for MaintenanceSchedule events.
/// Implement this trait to react to MaintenanceSchedule lifecycle events.
pub trait MaintenanceScheduleEventHandler: EventHandler<MaintenanceScheduleEvent> {}
