//! Event handler trait for MaintenanceStage events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaintenanceStageEvent;

/// Event handler for MaintenanceStage events.
/// Implement this trait to react to MaintenanceStage lifecycle events.
pub trait MaintenanceStageEventHandler: EventHandler<MaintenanceStageEvent> {}
