//! Domain events for MaintenanceVisitPart entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MaintenanceVisitPart;

/// Domain events for MaintenanceVisitPart — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MaintenanceVisitPart>)` variant.
pub type MaintenanceVisitPartEvent = CrudEvent<MaintenanceVisitPart>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MaintenanceVisitPart events.
pub type MaintenanceVisitPartEventPublisher = Arc<dyn CrudEventPublisher<MaintenanceVisitPart> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMaintenanceVisitPartEventPublisher = NoOpCrudEventPublisher<MaintenanceVisitPart>;
