//! Event handler trait for MaintenanceVisit events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaintenanceVisitEvent;

/// Event handler for MaintenanceVisit events.
/// Implement this trait to react to MaintenanceVisit lifecycle events.
pub trait MaintenanceVisitEventHandler: EventHandler<MaintenanceVisitEvent> {}
