//! Domain events for MaintenanceVisit entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MaintenanceVisit;

/// Domain events for MaintenanceVisit — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MaintenanceVisit>)` variant.
pub type MaintenanceVisitEvent = CrudEvent<MaintenanceVisit>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MaintenanceVisit events.
pub type MaintenanceVisitEventPublisher = Arc<dyn CrudEventPublisher<MaintenanceVisit> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMaintenanceVisitEventPublisher = NoOpCrudEventPublisher<MaintenanceVisit>;
