//! Domain events for MaintenanceSchedule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MaintenanceSchedule;

/// Domain events for MaintenanceSchedule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MaintenanceSchedule>)` variant.
pub type MaintenanceScheduleEvent = CrudEvent<MaintenanceSchedule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MaintenanceSchedule events.
pub type MaintenanceScheduleEventPublisher = Arc<dyn CrudEventPublisher<MaintenanceSchedule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMaintenanceScheduleEventPublisher = NoOpCrudEventPublisher<MaintenanceSchedule>;
