//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod maintenance_schedule_events;
pub mod maintenance_schedule_event_handlers;
pub mod maintenance_visit_events;
pub mod maintenance_visit_event_handlers;
pub mod maintenance_visit_part_events;
pub mod maintenance_visit_part_event_handlers;

pub use maintenance_schedule_events::{MaintenanceScheduleEvent, MaintenanceScheduleEventPublisher, NoopMaintenanceScheduleEventPublisher};
pub use maintenance_schedule_event_handlers::MaintenanceScheduleEventHandler;
pub use maintenance_visit_events::{MaintenanceVisitEvent, MaintenanceVisitEventPublisher, NoopMaintenanceVisitEventPublisher};
pub use maintenance_visit_event_handlers::MaintenanceVisitEventHandler;
pub use maintenance_visit_part_events::{MaintenanceVisitPartEvent, MaintenanceVisitPartEventPublisher, NoopMaintenanceVisitPartEventPublisher};
pub use maintenance_visit_part_event_handlers::MaintenanceVisitPartEventHandler;

// <<< CUSTOM
// END CUSTOM
