//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod maintenance_request_events;
pub mod maintenance_request_event_handlers;
pub mod maintenance_schedule_events;
pub mod maintenance_schedule_event_handlers;
pub mod maintenance_stage_events;
pub mod maintenance_stage_event_handlers;
pub mod maintenance_visit_events;
pub mod maintenance_visit_event_handlers;
pub mod maintenance_visit_part_events;
pub mod maintenance_visit_part_event_handlers;

pub use maintenance_request_events::{MaintenanceRequestEvent, MaintenanceRequestEventPublisher, NoopMaintenanceRequestEventPublisher};
pub use maintenance_request_event_handlers::MaintenanceRequestEventHandler;
pub use maintenance_schedule_events::{MaintenanceScheduleEvent, MaintenanceScheduleEventPublisher, NoopMaintenanceScheduleEventPublisher};
pub use maintenance_schedule_event_handlers::MaintenanceScheduleEventHandler;
pub use maintenance_stage_events::{MaintenanceStageEvent, MaintenanceStageEventPublisher, NoopMaintenanceStageEventPublisher};
pub use maintenance_stage_event_handlers::MaintenanceStageEventHandler;
pub use maintenance_visit_events::{MaintenanceVisitEvent, MaintenanceVisitEventPublisher, NoopMaintenanceVisitEventPublisher};
pub use maintenance_visit_event_handlers::MaintenanceVisitEventHandler;
pub use maintenance_visit_part_events::{MaintenanceVisitPartEvent, MaintenanceVisitPartEventPublisher, NoopMaintenanceVisitPartEventPublisher};
pub use maintenance_visit_part_event_handlers::MaintenanceVisitPartEventHandler;

// <<< CUSTOM
// END CUSTOM
