//! Event subscriber type aliases for Maintenance module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::MaintenanceScheduleEvent;
use crate::domain::event::MaintenanceVisitEvent;
use crate::domain::event::MaintenanceVisitPartEvent;

/// Subscriber for MaintenanceSchedule events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MaintenanceScheduleEventSubscriber = GenericEventSubscriber<MaintenanceScheduleEvent>;

/// Subscriber for MaintenanceVisit events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MaintenanceVisitEventSubscriber = GenericEventSubscriber<MaintenanceVisitEvent>;

/// Subscriber for MaintenanceVisitPart events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MaintenanceVisitPartEventSubscriber = GenericEventSubscriber<MaintenanceVisitPartEvent>;

// <<< CUSTOM
// END CUSTOM
