//! MaintenanceVisitPart seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MaintenanceVisitPart data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAINTENANCEVISITPART SEEDER
// ============================================================================

/// Seeder for maintenance_visit_part
pub struct SeedMaintenanceVisitPartSeeder;

impl SeedMaintenanceVisitPartSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMaintenanceVisitPartSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMaintenanceVisitPartSeeder {
    fn name(&self) -> &'static str {
        "SeedMaintenanceVisitPartSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if maintenance.maintenance_visit_parts table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM maintenance.maintenance_visit_parts")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/maintenance_visit_part_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM maintenance.maintenance_visit_parts")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

