//! Repository trait for MaintenanceSchedule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MaintenanceSchedule aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MaintenanceSchedule, MaintenanceScheduleStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceSchedulePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MaintenanceSchedulePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MaintenanceSchedulePaginatedResult {
    pub data: Vec<MaintenanceSchedule>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceScheduleFilter {
    pub company_id: Option<Uuid>,
    pub asset_id: Option<Uuid>,
    pub name: Option<String>,
    pub status: Option<MaintenanceScheduleStatus>,
}

impl MaintenanceScheduleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.asset_id.is_some() || self.name.is_some() || self.status.is_some()
    }
}

/// Repository trait for MaintenanceSchedule aggregate
///
/// This trait defines the persistence contract for MaintenanceSchedule entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MaintenanceScheduleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new maintenance_schedule entity
    async fn save(&self, entity: &MaintenanceSchedule) -> Result<MaintenanceSchedule>;

    /// Find maintenance_schedule by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MaintenanceSchedule>>;

    /// Find all maintenance_schedule entities
    async fn find_all(&self) -> Result<Vec<MaintenanceSchedule>>;

    /// Update maintenance_schedule by ID
    async fn update(&self, id: &str, entity: &MaintenanceSchedule) -> Result<Option<MaintenanceSchedule>>;

    /// Delete maintenance_schedule by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List maintenance_schedule with pagination
    async fn list(&self, params: MaintenanceSchedulePaginationParams) -> Result<MaintenanceSchedulePaginatedResult>;

    /// List maintenance_schedule with pagination and filters
    async fn list_with_filters(&self, params: MaintenanceSchedulePaginationParams, filters: MaintenanceScheduleFilter) -> Result<MaintenanceSchedulePaginatedResult>;

    /// Count all maintenance_schedule entities
    async fn count(&self) -> Result<u64>;

    /// Count maintenance_schedule entities matching filters
    async fn count_with_filters(&self, filters: MaintenanceScheduleFilter) -> Result<u64>;

    /// Check if maintenance_schedule exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete maintenance_schedule by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted maintenance_schedule by ID
    async fn restore(&self, id: &str) -> Result<Option<MaintenanceSchedule>>;

    /// List soft-deleted maintenance_schedule entities
    async fn list_deleted(&self, params: MaintenanceSchedulePaginationParams) -> Result<MaintenanceSchedulePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save maintenance_schedule entities
    async fn bulk_save(&self, entities: &[MaintenanceSchedule]) -> Result<Vec<MaintenanceSchedule>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
