//! Repository trait for MaintenanceVisit aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MaintenanceVisit aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MaintenanceVisit, MaintenanceType, VisitStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceVisitPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MaintenanceVisitPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MaintenanceVisitPaginatedResult {
    pub data: Vec<MaintenanceVisit>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceVisitFilter {
    pub company_id: Option<Uuid>,
    pub asset_id: Option<Uuid>,
    pub schedule_id: Option<Uuid>,
    pub maintenance_type: Option<MaintenanceType>,
    pub status: Option<VisitStatus>,
    pub warehouse_id: Option<Uuid>,
    pub warranty_claim_id: Option<Uuid>,
    pub maintenance_expense_account_id: Option<Uuid>,
    pub parts_inventory_account_id: Option<Uuid>,
    pub labor_payable_account_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub notes: Option<String>,
}

impl MaintenanceVisitFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.asset_id.is_some() || self.schedule_id.is_some() || self.maintenance_type.is_some() || self.status.is_some() || self.warehouse_id.is_some() || self.warranty_claim_id.is_some() || self.maintenance_expense_account_id.is_some() || self.parts_inventory_account_id.is_some() || self.labor_payable_account_id.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.notes.is_some()
    }
}

/// Repository trait for MaintenanceVisit aggregate
///
/// This trait defines the persistence contract for MaintenanceVisit entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MaintenanceVisitRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new maintenance_visit entity
    async fn save(&self, entity: &MaintenanceVisit) -> Result<MaintenanceVisit>;

    /// Find maintenance_visit by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MaintenanceVisit>>;

    /// Find all maintenance_visit entities
    async fn find_all(&self) -> Result<Vec<MaintenanceVisit>>;

    /// Update maintenance_visit by ID
    async fn update(&self, id: &str, entity: &MaintenanceVisit) -> Result<Option<MaintenanceVisit>>;

    /// Delete maintenance_visit by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List maintenance_visit with pagination
    async fn list(&self, params: MaintenanceVisitPaginationParams) -> Result<MaintenanceVisitPaginatedResult>;

    /// List maintenance_visit with pagination and filters
    async fn list_with_filters(&self, params: MaintenanceVisitPaginationParams, filters: MaintenanceVisitFilter) -> Result<MaintenanceVisitPaginatedResult>;

    /// Count all maintenance_visit entities
    async fn count(&self) -> Result<u64>;

    /// Count maintenance_visit entities matching filters
    async fn count_with_filters(&self, filters: MaintenanceVisitFilter) -> Result<u64>;

    /// Check if maintenance_visit exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete maintenance_visit by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted maintenance_visit by ID
    async fn restore(&self, id: &str) -> Result<Option<MaintenanceVisit>>;

    /// List soft-deleted maintenance_visit entities
    async fn list_deleted(&self, params: MaintenanceVisitPaginationParams) -> Result<MaintenanceVisitPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save maintenance_visit entities
    async fn bulk_save(&self, entities: &[MaintenanceVisit]) -> Result<Vec<MaintenanceVisit>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
