//! Repository trait for MaintenanceStage aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MaintenanceStage aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::MaintenanceStage;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceStagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MaintenanceStagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MaintenanceStagePaginatedResult {
    pub data: Vec<MaintenanceStage>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceStageFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub fold: Option<bool>,
    pub done: Option<bool>,
}

impl MaintenanceStageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.fold.is_some() || self.done.is_some()
    }
}

/// Repository trait for MaintenanceStage aggregate
///
/// This trait defines the persistence contract for MaintenanceStage entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MaintenanceStageRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new maintenance_stage entity
    async fn save(&self, entity: &MaintenanceStage) -> Result<MaintenanceStage>;

    /// Find maintenance_stage by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MaintenanceStage>>;

    /// Find all maintenance_stage entities
    async fn find_all(&self) -> Result<Vec<MaintenanceStage>>;

    /// Update maintenance_stage by ID
    async fn update(&self, id: &str, entity: &MaintenanceStage) -> Result<Option<MaintenanceStage>>;

    /// Delete maintenance_stage by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List maintenance_stage with pagination
    async fn list(&self, params: MaintenanceStagePaginationParams) -> Result<MaintenanceStagePaginatedResult>;

    /// List maintenance_stage with pagination and filters
    async fn list_with_filters(&self, params: MaintenanceStagePaginationParams, filters: MaintenanceStageFilter) -> Result<MaintenanceStagePaginatedResult>;

    /// Count all maintenance_stage entities
    async fn count(&self) -> Result<u64>;

    /// Count maintenance_stage entities matching filters
    async fn count_with_filters(&self, filters: MaintenanceStageFilter) -> Result<u64>;

    /// Check if maintenance_stage exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete maintenance_stage by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted maintenance_stage by ID
    async fn restore(&self, id: &str) -> Result<Option<MaintenanceStage>>;

    /// List soft-deleted maintenance_stage entities
    async fn list_deleted(&self, params: MaintenanceStagePaginationParams) -> Result<MaintenanceStagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save maintenance_stage entities
    async fn bulk_save(&self, entities: &[MaintenanceStage]) -> Result<Vec<MaintenanceStage>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
