//! Repository trait for MaintenanceRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MaintenanceRequest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MaintenanceRequest, MaintenanceType, RepeatType, RepeatUnit, RequestKanbanState, RequestPriority};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceRequestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MaintenanceRequestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MaintenanceRequestPaginatedResult {
    pub data: Vec<MaintenanceRequest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceRequestFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub owner_user_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub asset_id: Option<Uuid>,
    pub stage_id: Option<Uuid>,
    pub kanban_state: Option<RequestKanbanState>,
    pub priority: Option<RequestPriority>,
    pub maintenance_type: Option<MaintenanceType>,
    pub recurring: Option<bool>,
    pub repeat_unit: Option<RepeatUnit>,
    pub repeat_type: Option<RepeatType>,
    pub successor_request_id: Option<Uuid>,
    pub successor_of_request_id: Option<Uuid>,
}

impl MaintenanceRequestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.description.is_some() || self.owner_user_id.is_some() || self.user_id.is_some() || self.asset_id.is_some() || self.stage_id.is_some() || self.kanban_state.is_some() || self.priority.is_some() || self.maintenance_type.is_some() || self.recurring.is_some() || self.repeat_unit.is_some() || self.repeat_type.is_some() || self.successor_request_id.is_some() || self.successor_of_request_id.is_some()
    }
}

/// Repository trait for MaintenanceRequest aggregate
///
/// This trait defines the persistence contract for MaintenanceRequest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MaintenanceRequestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new maintenance_request entity
    async fn save(&self, entity: &MaintenanceRequest) -> Result<MaintenanceRequest>;

    /// Find maintenance_request by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MaintenanceRequest>>;

    /// Find all maintenance_request entities
    async fn find_all(&self) -> Result<Vec<MaintenanceRequest>>;

    /// Update maintenance_request by ID
    async fn update(&self, id: &str, entity: &MaintenanceRequest) -> Result<Option<MaintenanceRequest>>;

    /// Delete maintenance_request by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List maintenance_request with pagination
    async fn list(&self, params: MaintenanceRequestPaginationParams) -> Result<MaintenanceRequestPaginatedResult>;

    /// List maintenance_request with pagination and filters
    async fn list_with_filters(&self, params: MaintenanceRequestPaginationParams, filters: MaintenanceRequestFilter) -> Result<MaintenanceRequestPaginatedResult>;

    /// Count all maintenance_request entities
    async fn count(&self) -> Result<u64>;

    /// Count maintenance_request entities matching filters
    async fn count_with_filters(&self, filters: MaintenanceRequestFilter) -> Result<u64>;

    /// Check if maintenance_request exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete maintenance_request by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted maintenance_request by ID
    async fn restore(&self, id: &str) -> Result<Option<MaintenanceRequest>>;

    /// List soft-deleted maintenance_request entities
    async fn list_deleted(&self, params: MaintenanceRequestPaginationParams) -> Result<MaintenanceRequestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save maintenance_request entities
    async fn bulk_save(&self, entities: &[MaintenanceRequest]) -> Result<Vec<MaintenanceRequest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
