//! Repository trait for MaintenanceVisitPart aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MaintenanceVisitPart aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::MaintenanceVisitPart;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceVisitPartPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MaintenanceVisitPartPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MaintenanceVisitPartPaginatedResult {
    pub data: Vec<MaintenanceVisitPart>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MaintenanceVisitPartFilter {
    pub visit_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
}

impl MaintenanceVisitPartFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.visit_id.is_some() || self.item_id.is_some()
    }
}

/// Repository trait for MaintenanceVisitPart aggregate
///
/// This trait defines the persistence contract for MaintenanceVisitPart entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MaintenanceVisitPartRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new maintenance_visit_part entity
    async fn save(&self, entity: &MaintenanceVisitPart) -> Result<MaintenanceVisitPart>;

    /// Find maintenance_visit_part by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MaintenanceVisitPart>>;

    /// Find all maintenance_visit_part entities
    async fn find_all(&self) -> Result<Vec<MaintenanceVisitPart>>;

    /// Update maintenance_visit_part by ID
    async fn update(&self, id: &str, entity: &MaintenanceVisitPart) -> Result<Option<MaintenanceVisitPart>>;

    /// Delete maintenance_visit_part by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List maintenance_visit_part with pagination
    async fn list(&self, params: MaintenanceVisitPartPaginationParams) -> Result<MaintenanceVisitPartPaginatedResult>;

    /// List maintenance_visit_part with pagination and filters
    async fn list_with_filters(&self, params: MaintenanceVisitPartPaginationParams, filters: MaintenanceVisitPartFilter) -> Result<MaintenanceVisitPartPaginatedResult>;

    /// Count all maintenance_visit_part entities
    async fn count(&self) -> Result<u64>;

    /// Count maintenance_visit_part entities matching filters
    async fn count_with_filters(&self, filters: MaintenanceVisitPartFilter) -> Result<u64>;

    /// Check if maintenance_visit_part exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete maintenance_visit_part by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted maintenance_visit_part by ID
    async fn restore(&self, id: &str) -> Result<Option<MaintenanceVisitPart>>;

    /// List soft-deleted maintenance_visit_part entities
    async fn list_deleted(&self, params: MaintenanceVisitPartPaginationParams) -> Result<MaintenanceVisitPartPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save maintenance_visit_part entities
    async fn bulk_save(&self, entities: &[MaintenanceVisitPart]) -> Result<Vec<MaintenanceVisitPart>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
