//! Repository for MaintenanceSchedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MaintenanceSchedule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MaintenanceSchedule;

/// Table name for MaintenanceSchedule entities
pub const TABLE_NAME: &str = "maintenance.maintenance_schedules";

/// Repository for MaintenanceSchedule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MaintenanceScheduleRepository(
    backbone_orm::GenericCrudRepository<MaintenanceSchedule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MaintenanceScheduleRepository {
    type Target = backbone_orm::GenericCrudRepository<MaintenanceSchedule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MaintenanceScheduleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MaintenanceScheduleRepository, MaintenanceSchedule, soft_delete);
