//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod maintenance_schedule_repository;
mod maintenance_visit_repository;
mod maintenance_visit_part_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use maintenance_schedule_repository::MaintenanceScheduleRepository;
pub use maintenance_visit_repository::MaintenanceVisitRepository;
pub use maintenance_visit_part_repository::MaintenanceVisitPartRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
