//! Validator for MaintenanceVisit entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MaintenanceVisit>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::MaintenanceVisit;

/// Validator type alias for MaintenanceVisit entities.
pub type MaintenanceVisitValidator = EntityValidator<MaintenanceVisit>;

/// Build a validator for MaintenanceVisit with all schema-defined field rules.
pub fn maintenance_visit_validator() -> MaintenanceVisitValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("notes", |e: &MaintenanceVisit| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
