//! Validator for MaintenanceVisitPart entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MaintenanceVisitPart>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::MaintenanceVisitPart;

/// Validator type alias for MaintenanceVisitPart entities.
pub type MaintenanceVisitPartValidator = EntityValidator<MaintenanceVisitPart>;

/// Build a validator for MaintenanceVisitPart with all schema-defined field rules.
pub fn maintenance_visit_part_validator() -> MaintenanceVisitPartValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
