//! Validator for MaintenanceStage entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MaintenanceStage>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::MaintenanceStage;

/// Validator type alias for MaintenanceStage entities.
pub type MaintenanceStageValidator = EntityValidator<MaintenanceStage>;

/// Build a validator for MaintenanceStage with all schema-defined field rules.
pub fn maintenance_stage_validator() -> MaintenanceStageValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MaintenanceStage| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
