//! Validator for MaintenanceRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MaintenanceRequest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::MaintenanceRequest;

/// Validator type alias for MaintenanceRequest entities.
pub type MaintenanceRequestValidator = EntityValidator<MaintenanceRequest>;

/// Build a validator for MaintenanceRequest with all schema-defined field rules.
pub fn maintenance_request_validator() -> MaintenanceRequestValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MaintenanceRequest| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &MaintenanceRequest| e.description.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: G-MT2 (implement in CUSTOM zone)
    // hook rule: G-MT3 (implement in CUSTOM zone)
    // hook rule: G-MT7 (implement in CUSTOM zone)
    // hook rule: G-MT8 (implement in CUSTOM zone)
    // hook rule: G-MT5 (implement in CUSTOM zone)
    // hook rule: G-MT6 (implement in CUSTOM zone)
    // hook rule: G-MT_STAGE_FK (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
