//! Auth configuration for MaintenanceVisit handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<MaintenanceVisit>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::MaintenanceVisitService;
use crate::domain::entity::MaintenanceVisit;

/// Permission string constants for MaintenanceVisit operations.
pub mod permissions {
    pub const LIST:        &str = "maintenance_visit:list";
    pub const READ:        &str = "maintenance_visit:read";
    pub const CREATE:      &str = "maintenance_visit:create";
    pub const UPDATE:      &str = "maintenance_visit:update";
    pub const DELETE:      &str = "maintenance_visit:delete";
    pub const RESTORE:     &str = "maintenance_visit:restore";
    pub const TRASH:       &str = "maintenance_visit:trash";
    pub const EMPTY_TRASH: &str = "maintenance_visit:empty_trash";
    pub const BULK_CREATE: &str = "maintenance_visit:bulk_create";
    pub const UPSERT:      &str = "maintenance_visit:upsert";
}

/// Resource policy for MaintenanceVisit — maps CRUD actions to permission strings.
pub struct MaintenanceVisitPolicy;

#[async_trait]
impl ResourcePolicy<MaintenanceVisit> for MaintenanceVisitPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &MaintenanceVisit,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for MaintenanceVisit handlers.
///
/// Wraps `MaintenanceVisitService` and checks `MaintenanceVisitPolicy` before delegating.
pub type MaintenanceVisitGuard = PermissionGuard<MaintenanceVisit>;

/// Service-integrated permission guard for MaintenanceVisit (for use in generated handlers).
pub type MaintenanceVisitServiceGuard = ServicePermissionGuard<MaintenanceVisit, MaintenanceVisitService, MaintenanceVisitPolicy>;

// <<< CUSTOM
// END CUSTOM
