//! Auth configuration for MaintenanceSchedule handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<MaintenanceSchedule>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::MaintenanceScheduleService;
use crate::domain::entity::MaintenanceSchedule;

/// Permission string constants for MaintenanceSchedule operations.
pub mod permissions {
    pub const LIST:        &str = "maintenance_schedule:list";
    pub const READ:        &str = "maintenance_schedule:read";
    pub const CREATE:      &str = "maintenance_schedule:create";
    pub const UPDATE:      &str = "maintenance_schedule:update";
    pub const DELETE:      &str = "maintenance_schedule:delete";
    pub const RESTORE:     &str = "maintenance_schedule:restore";
    pub const TRASH:       &str = "maintenance_schedule:trash";
    pub const EMPTY_TRASH: &str = "maintenance_schedule:empty_trash";
    pub const BULK_CREATE: &str = "maintenance_schedule:bulk_create";
    pub const UPSERT:      &str = "maintenance_schedule:upsert";
}

/// Resource policy for MaintenanceSchedule — maps CRUD actions to permission strings.
pub struct MaintenanceSchedulePolicy;

#[async_trait]
impl ResourcePolicy<MaintenanceSchedule> for MaintenanceSchedulePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &MaintenanceSchedule,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for MaintenanceSchedule handlers.
///
/// Wraps `MaintenanceScheduleService` and checks `MaintenanceSchedulePolicy` before delegating.
pub type MaintenanceScheduleGuard = PermissionGuard<MaintenanceSchedule>;

/// Service-integrated permission guard for MaintenanceSchedule (for use in generated handlers).
pub type MaintenanceScheduleServiceGuard = ServicePermissionGuard<MaintenanceSchedule, MaintenanceScheduleService, MaintenanceSchedulePolicy>;

// <<< CUSTOM
// END CUSTOM
