//! Auth configuration for MaintenanceVisitPart handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<MaintenanceVisitPart>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::MaintenanceVisitPartService;
use crate::domain::entity::MaintenanceVisitPart;

/// Permission string constants for MaintenanceVisitPart operations.
pub mod permissions {
    pub const LIST:        &str = "maintenance_visit_part:list";
    pub const READ:        &str = "maintenance_visit_part:read";
    pub const CREATE:      &str = "maintenance_visit_part:create";
    pub const UPDATE:      &str = "maintenance_visit_part:update";
    pub const DELETE:      &str = "maintenance_visit_part:delete";
    pub const RESTORE:     &str = "maintenance_visit_part:restore";
    pub const TRASH:       &str = "maintenance_visit_part:trash";
    pub const EMPTY_TRASH: &str = "maintenance_visit_part:empty_trash";
    pub const BULK_CREATE: &str = "maintenance_visit_part:bulk_create";
    pub const UPSERT:      &str = "maintenance_visit_part:upsert";
}

/// Resource policy for MaintenanceVisitPart — maps CRUD actions to permission strings.
pub struct MaintenanceVisitPartPolicy;

#[async_trait]
impl ResourcePolicy<MaintenanceVisitPart> for MaintenanceVisitPartPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &MaintenanceVisitPart,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for MaintenanceVisitPart handlers.
///
/// Wraps `MaintenanceVisitPartService` and checks `MaintenanceVisitPartPolicy` before delegating.
pub type MaintenanceVisitPartGuard = PermissionGuard<MaintenanceVisitPart>;

/// Service-integrated permission guard for MaintenanceVisitPart (for use in generated handlers).
pub type MaintenanceVisitPartServiceGuard = ServicePermissionGuard<MaintenanceVisitPart, MaintenanceVisitPartService, MaintenanceVisitPartPolicy>;

// <<< CUSTOM
// END CUSTOM
