//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod maintenance_schedule_auth;
pub mod maintenance_visit_auth;
pub mod maintenance_visit_part_auth;

pub use maintenance_schedule_auth::{MaintenanceSchedulePolicy, MaintenanceScheduleGuard, MaintenanceScheduleServiceGuard};
pub use maintenance_visit_auth::{MaintenanceVisitPolicy, MaintenanceVisitGuard, MaintenanceVisitServiceGuard};
pub use maintenance_visit_part_auth::{MaintenanceVisitPartPolicy, MaintenanceVisitPartGuard, MaintenanceVisitPartServiceGuard};

// <<< CUSTOM
// END CUSTOM
