//! MaintenanceRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MaintenanceRequest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAINTENANCEREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MaintenanceRequest
pub struct MaintenanceRequestTestData;

impl TestDataGenerator for MaintenanceRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "request_date": Utc::now().format("%Y-%m-%d").to_string(),
            "schedule_date": null,
            "schedule_end": null,
            "close_date": null,
            "duration": 0,
            "owner_user_id": null,
            "user_id": null,
            "asset_id": null,
            "stage_id": Uuid::new_v4().to_string(),
            "kanban_state": "normal",
            "priority": "very_low",
            "maintenance_type": "preventive",
            "recurring": false,
            "repeat_interval": 1,
            "repeat_unit": "day",
            "repeat_type": "forever",
            "repeat_until": null,
            "successor_request_id": null,
            "successor_of_request_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "request_date": Utc::now().format("%Y-%m-%d").to_string(),
            "schedule_date": null,
            "schedule_end": null,
            "close_date": null,
            "duration": 0,
            "owner_user_id": null,
            "user_id": null,
            "asset_id": null,
            "stage_id": Uuid::new_v4().to_string(),
            "kanban_state": "normal",
            "priority": "very_low",
            "maintenance_type": "preventive",
            "recurring": false,
            "repeat_interval": 1,
            "repeat_unit": "day",
            "repeat_type": "forever",
            "repeat_until": null,
            "successor_request_id": null,
            "successor_of_request_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/maintenance_stages", &super::maintenance_stage_api_test::MaintenanceStageTestData).await {
            deps.push(("stage_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// MAINTENANCEREQUEST API TEST
// ============================================================================

/// MaintenanceRequest API test suite
pub struct MaintenanceRequestApiTest {
    inner: GenericCrudTest<MaintenanceRequestTestData>,
}

impl MaintenanceRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/maintenance_requests", "MaintenanceRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MaintenanceRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MaintenanceRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_maintenance_request_crud() {
        let mut test = MaintenanceRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MaintenanceRequest specific tests here
// <<< CUSTOM TESTS END >>>
