//! Maintenance Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::MaintenanceRequestService;
use crate::application::service::MaintenanceScheduleService;
use crate::application::service::MaintenanceStageService;
use crate::application::service::MaintenanceVisitService;
use crate::application::service::MaintenanceVisitPartService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// MaintenanceRequest service
    pub maintenance_request_service: Arc<MaintenanceRequestService>,
    /// MaintenanceSchedule service
    pub maintenance_schedule_service: Arc<MaintenanceScheduleService>,
    /// MaintenanceStage service
    pub maintenance_stage_service: Arc<MaintenanceStageService>,
    /// MaintenanceVisit service
    pub maintenance_visit_service: Arc<MaintenanceVisitService>,
    /// MaintenanceVisitPart service
    pub maintenance_visit_part_service: Arc<MaintenanceVisitPartService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        maintenance_request_service: Arc<MaintenanceRequestService>,
        maintenance_schedule_service: Arc<MaintenanceScheduleService>,
        maintenance_stage_service: Arc<MaintenanceStageService>,
        maintenance_visit_service: Arc<MaintenanceVisitService>,
        maintenance_visit_part_service: Arc<MaintenanceVisitPartService>
    ) -> Self {
        Self {
            maintenance_request_service,
            maintenance_schedule_service,
            maintenance_stage_service,
            maintenance_visit_service,
            maintenance_visit_part_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::MaintenanceModule) -> Self {
        Self {
            maintenance_request_service: module.maintenance_request_service.clone(),
            maintenance_schedule_service: module.maintenance_schedule_service.clone(),
            maintenance_stage_service: module.maintenance_stage_service.clone(),
            maintenance_visit_service: module.maintenance_visit_service.clone(),
            maintenance_visit_part_service: module.maintenance_visit_part_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    maintenance_request_service: Option<Arc<MaintenanceRequestService>>,
    maintenance_schedule_service: Option<Arc<MaintenanceScheduleService>>,
    maintenance_stage_service: Option<Arc<MaintenanceStageService>>,
    maintenance_visit_service: Option<Arc<MaintenanceVisitService>>,
    maintenance_visit_part_service: Option<Arc<MaintenanceVisitPartService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the MaintenanceRequest service.
    pub fn with_maintenance_request_service(mut self, service: Arc<MaintenanceRequestService>) -> Self {
        self.maintenance_request_service = Some(service);
        self
    }

    /// Set the MaintenanceSchedule service.
    pub fn with_maintenance_schedule_service(mut self, service: Arc<MaintenanceScheduleService>) -> Self {
        self.maintenance_schedule_service = Some(service);
        self
    }

    /// Set the MaintenanceStage service.
    pub fn with_maintenance_stage_service(mut self, service: Arc<MaintenanceStageService>) -> Self {
        self.maintenance_stage_service = Some(service);
        self
    }

    /// Set the MaintenanceVisit service.
    pub fn with_maintenance_visit_service(mut self, service: Arc<MaintenanceVisitService>) -> Self {
        self.maintenance_visit_service = Some(service);
        self
    }

    /// Set the MaintenanceVisitPart service.
    pub fn with_maintenance_visit_part_service(mut self, service: Arc<MaintenanceVisitPartService>) -> Self {
        self.maintenance_visit_part_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            maintenance_request_service: self.maintenance_request_service.expect("maintenance_request_service is required"),
            maintenance_schedule_service: self.maintenance_schedule_service.expect("maintenance_schedule_service is required"),
            maintenance_stage_service: self.maintenance_stage_service.expect("maintenance_stage_service is required"),
            maintenance_visit_service: self.maintenance_visit_service.expect("maintenance_visit_service is required"),
            maintenance_visit_part_service: self.maintenance_visit_part_service.expect("maintenance_visit_part_service is required"),
        }
    }
}
