//! Maintenance Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::MaintenanceScheduleService;
pub use application::service::MaintenanceVisitService;
pub use application::service::MaintenanceVisitPartService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Maintenance module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let maintenance = MaintenanceModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = maintenance.all_crud_routes();
/// ```
pub struct MaintenanceModule {
    pub maintenance_schedule_service: Arc<MaintenanceScheduleService>,
    pub maintenance_visit_service: Arc<MaintenanceVisitService>,
    pub maintenance_visit_part_service: Arc<MaintenanceVisitPartService>,
}

impl MaintenanceModule {
    /// Create a new module builder
    pub fn builder() -> MaintenanceModuleBuilder {
        MaintenanceModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_maintenance_schedule_routes,
            create_maintenance_visit_routes,
            create_maintenance_visit_part_routes,
        };

        Router::new()
            .merge(create_maintenance_schedule_routes(self.maintenance_schedule_service.clone()))
            .merge(create_maintenance_visit_routes(self.maintenance_visit_service.clone()))
            .merge(create_maintenance_visit_part_routes(self.maintenance_visit_part_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for MaintenanceModule
pub struct MaintenanceModuleBuilder {
    db_pool: Option<PgPool>,
}

impl MaintenanceModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<MaintenanceModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // MaintenanceSchedule service
        let maintenance_schedule_repository = Arc::new(MaintenanceScheduleRepository::new(db_pool.clone()));
        let maintenance_schedule_service = Arc::new(MaintenanceScheduleService::with_repository(maintenance_schedule_repository.clone()));

        // MaintenanceVisit service
        let maintenance_visit_repository = Arc::new(MaintenanceVisitRepository::new(db_pool.clone()));
        let maintenance_visit_service = Arc::new(MaintenanceVisitService::with_repository(maintenance_visit_repository.clone()));

        // MaintenanceVisitPart service
        let maintenance_visit_part_repository = Arc::new(MaintenanceVisitPartRepository::new(db_pool.clone()));
        let maintenance_visit_part_service = Arc::new(MaintenanceVisitPartService::with_repository(maintenance_visit_part_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(MaintenanceModule {
            maintenance_schedule_service,
            maintenance_visit_service,
            maintenance_visit_part_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for MaintenanceModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
