//! Use case type aliases for MaintenanceVisitPart aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateMaintenanceVisitPartDto, UpdateMaintenanceVisitPartDto};
use crate::application::service::MaintenanceVisitPartService;
use crate::domain::entity::MaintenanceVisitPart;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateMaintenanceVisitPartUseCase = CreateUseCase<MaintenanceVisitPart, CreateMaintenanceVisitPartDto, MaintenanceVisitPartService>;
pub type UpdateMaintenanceVisitPartUseCase = UpdateUseCase<MaintenanceVisitPart, UpdateMaintenanceVisitPartDto, MaintenanceVisitPartService>;
pub type GetMaintenanceVisitPartUseCase    = GetUseCase<MaintenanceVisitPart, MaintenanceVisitPartService>;
pub type DeleteMaintenanceVisitPartUseCase = DeleteUseCase<MaintenanceVisitPart, MaintenanceVisitPartService>;
pub type ListMaintenanceVisitPartUseCase   = ListUseCase<MaintenanceVisitPart, MaintenanceVisitPartService>;

// <<< CUSTOM
// END CUSTOM
