//! Use case type aliases for MaintenanceVisit aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateMaintenanceVisitDto, UpdateMaintenanceVisitDto};
use crate::application::service::MaintenanceVisitService;
use crate::domain::entity::MaintenanceVisit;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateMaintenanceVisitUseCase = CreateUseCase<MaintenanceVisit, CreateMaintenanceVisitDto, MaintenanceVisitService>;
pub type UpdateMaintenanceVisitUseCase = UpdateUseCase<MaintenanceVisit, UpdateMaintenanceVisitDto, MaintenanceVisitService>;
pub type GetMaintenanceVisitUseCase    = GetUseCase<MaintenanceVisit, MaintenanceVisitService>;
pub type DeleteMaintenanceVisitUseCase = DeleteUseCase<MaintenanceVisit, MaintenanceVisitService>;
pub type ListMaintenanceVisitUseCase   = ListUseCase<MaintenanceVisit, MaintenanceVisitService>;

// <<< CUSTOM
// END CUSTOM
