//! Use case type aliases for MaintenanceSchedule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateMaintenanceScheduleDto, UpdateMaintenanceScheduleDto};
use crate::application::service::MaintenanceScheduleService;
use crate::domain::entity::MaintenanceSchedule;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateMaintenanceScheduleUseCase = CreateUseCase<MaintenanceSchedule, CreateMaintenanceScheduleDto, MaintenanceScheduleService>;
pub type UpdateMaintenanceScheduleUseCase = UpdateUseCase<MaintenanceSchedule, UpdateMaintenanceScheduleDto, MaintenanceScheduleService>;
pub type GetMaintenanceScheduleUseCase    = GetUseCase<MaintenanceSchedule, MaintenanceScheduleService>;
pub type DeleteMaintenanceScheduleUseCase = DeleteUseCase<MaintenanceSchedule, MaintenanceScheduleService>;
pub type ListMaintenanceScheduleUseCase   = ListUseCase<MaintenanceSchedule, MaintenanceScheduleService>;

// <<< CUSTOM
// END CUSTOM
