//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod maintenance_schedule_usecases;
pub mod maintenance_visit_usecases;
pub mod maintenance_visit_part_usecases;

pub use maintenance_schedule_usecases::{
    CreateMaintenanceScheduleUseCase, UpdateMaintenanceScheduleUseCase, GetMaintenanceScheduleUseCase,
    DeleteMaintenanceScheduleUseCase, ListMaintenanceScheduleUseCase,
};
pub use maintenance_visit_usecases::{
    CreateMaintenanceVisitUseCase, UpdateMaintenanceVisitUseCase, GetMaintenanceVisitUseCase,
    DeleteMaintenanceVisitUseCase, ListMaintenanceVisitUseCase,
};
pub use maintenance_visit_part_usecases::{
    CreateMaintenanceVisitPartUseCase, UpdateMaintenanceVisitPartUseCase, GetMaintenanceVisitPartUseCase,
    DeleteMaintenanceVisitPartUseCase, ListMaintenanceVisitPartUseCase,
};

// <<< CUSTOM
// END CUSTOM
